// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: contracts/kitchen/kitchen.proto

package KitchenProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeFood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListOfFood []string `protobuf:"bytes,2,rep,name=listOfFood,proto3" json:"listOfFood,omitempty"`
}

func (x *MakeFood) Reset() {
	*x = MakeFood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_kitchen_kitchen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeFood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeFood) ProtoMessage() {}

func (x *MakeFood) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_kitchen_kitchen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeFood.ProtoReflect.Descriptor instead.
func (*MakeFood) Descriptor() ([]byte, []int) {
	return file_contracts_kitchen_kitchen_proto_rawDescGZIP(), []int{0}
}

func (x *MakeFood) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MakeFood) GetListOfFood() []string {
	if x != nil {
		return x.ListOfFood
	}
	return nil
}

type OrderReceived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OrderReceived) Reset() {
	*x = OrderReceived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_kitchen_kitchen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReceived) ProtoMessage() {}

func (x *OrderReceived) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_kitchen_kitchen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReceived.ProtoReflect.Descriptor instead.
func (*OrderReceived) Descriptor() ([]byte, []int) {
	return file_contracts_kitchen_kitchen_proto_rawDescGZIP(), []int{1}
}

func (x *OrderReceived) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contracts_kitchen_kitchen_proto protoreflect.FileDescriptor

var file_contracts_kitchen_kitchen_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x6b, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x6e, 0x2f, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3a, 0x0a, 0x08, 0x4d, 0x61, 0x6b, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c,
	0x69, 0x73, 0x74, 0x4f, 0x66, 0x46, 0x6f, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x46, 0x6f, 0x6f, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4d, 0x0a, 0x0e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x43, 0x6f, 0x6f, 0x6b,
	0x12, 0x16, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x61, 0x6b, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x1a, 0x1b, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x61, 0x6e, 0x39, 0x36, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2f, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contracts_kitchen_kitchen_proto_rawDescOnce sync.Once
	file_contracts_kitchen_kitchen_proto_rawDescData = file_contracts_kitchen_kitchen_proto_rawDesc
)

func file_contracts_kitchen_kitchen_proto_rawDescGZIP() []byte {
	file_contracts_kitchen_kitchen_proto_rawDescOnce.Do(func() {
		file_contracts_kitchen_kitchen_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_kitchen_kitchen_proto_rawDescData)
	})
	return file_contracts_kitchen_kitchen_proto_rawDescData
}

var file_contracts_kitchen_kitchen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_kitchen_kitchen_proto_goTypes = []interface{}{
	(*MakeFood)(nil),      // 0: KitchenProto.MakeFood
	(*OrderReceived)(nil), // 1: KitchenProto.OrderReceived
}
var file_contracts_kitchen_kitchen_proto_depIdxs = []int32{
	0, // 0: KitchenProto.KitchenService.Cook:input_type -> KitchenProto.MakeFood
	1, // 1: KitchenProto.KitchenService.Cook:output_type -> KitchenProto.OrderReceived
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_kitchen_kitchen_proto_init() }
func file_contracts_kitchen_kitchen_proto_init() {
	if File_contracts_kitchen_kitchen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contracts_kitchen_kitchen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeFood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_kitchen_kitchen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReceived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_kitchen_kitchen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_kitchen_kitchen_proto_goTypes,
		DependencyIndexes: file_contracts_kitchen_kitchen_proto_depIdxs,
		MessageInfos:      file_contracts_kitchen_kitchen_proto_msgTypes,
	}.Build()
	File_contracts_kitchen_kitchen_proto = out.File
	file_contracts_kitchen_kitchen_proto_rawDesc = nil
	file_contracts_kitchen_kitchen_proto_goTypes = nil
	file_contracts_kitchen_kitchen_proto_depIdxs = nil
}
