// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: contracts/waiter.proto

package WaiterProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListOfFood   []string `protobuf:"bytes,2,rep,name=listOfFood,proto3" json:"listOfFood,omitempty"`
	ListOfDrinks []string `protobuf:"bytes,3,rep,name=listOfDrinks,proto3" json:"listOfDrinks,omitempty"`
	TableNumber  int64    `protobuf:"varint,4,opt,name=tableNumber,proto3" json:"tableNumber,omitempty"`
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_waiter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_waiter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_contracts_waiter_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderRequest) GetListOfFood() []string {
	if x != nil {
		return x.ListOfFood
	}
	return nil
}

func (x *OrderRequest) GetListOfDrinks() []string {
	if x != nil {
		return x.ListOfDrinks
	}
	return nil
}

func (x *OrderRequest) GetTableNumber() int64 {
	if x != nil {
		return x.TableNumber
	}
	return 0
}

type OrderAcknowledged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID int64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
}

func (x *OrderAcknowledged) Reset() {
	*x = OrderAcknowledged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_waiter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderAcknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAcknowledged) ProtoMessage() {}

func (x *OrderAcknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_waiter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAcknowledged.ProtoReflect.Descriptor instead.
func (*OrderAcknowledged) Descriptor() ([]byte, []int) {
	return file_contracts_waiter_proto_rawDescGZIP(), []int{1}
}

func (x *OrderAcknowledged) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

var File_contracts_waiter_proto protoreflect.FileDescriptor

var file_contracts_waiter_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x77, 0x61, 0x69, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x57, 0x61, 0x69, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x46, 0x6f, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74,
	0x4f, 0x66, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69,
	0x73, 0x74, 0x4f, 0x66, 0x44, 0x72, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x11,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x32, 0x53, 0x0a, 0x0d, 0x57,
	0x61, 0x69, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x05,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x64,
	0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x72, 0x61, 0x6e, 0x39, 0x36, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x57, 0x61,
	0x69, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_contracts_waiter_proto_rawDescOnce sync.Once
	file_contracts_waiter_proto_rawDescData = file_contracts_waiter_proto_rawDesc
)

func file_contracts_waiter_proto_rawDescGZIP() []byte {
	file_contracts_waiter_proto_rawDescOnce.Do(func() {
		file_contracts_waiter_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_waiter_proto_rawDescData)
	})
	return file_contracts_waiter_proto_rawDescData
}

var file_contracts_waiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contracts_waiter_proto_goTypes = []interface{}{
	(*OrderRequest)(nil),      // 0: WaiterProto.OrderRequest
	(*OrderAcknowledged)(nil), // 1: WaiterProto.OrderAcknowledged
}
var file_contracts_waiter_proto_depIdxs = []int32{
	0, // 0: WaiterProto.WaiterService.Order:input_type -> WaiterProto.OrderRequest
	1, // 1: WaiterProto.WaiterService.Order:output_type -> WaiterProto.OrderAcknowledged
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contracts_waiter_proto_init() }
func file_contracts_waiter_proto_init() {
	if File_contracts_waiter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contracts_waiter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_waiter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderAcknowledged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_waiter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_waiter_proto_goTypes,
		DependencyIndexes: file_contracts_waiter_proto_depIdxs,
		MessageInfos:      file_contracts_waiter_proto_msgTypes,
	}.Build()
	File_contracts_waiter_proto = out.File
	file_contracts_waiter_proto_rawDesc = nil
	file_contracts_waiter_proto_goTypes = nil
	file_contracts_waiter_proto_depIdxs = nil
}
